env:
  browser: true
  es2021: true
  node: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: { declaration-empty-line-before: null
  plugin/rational-order:
    - true
    - empty-line-between-groups: true }
