extends:
  - stylelint-config-standard
  - stylelint-config-rational-order

plugins:
  - stylelint-order

rules:
  declaration-empty-line-before: null
  plugin/rational-order:
    - true
    - empty-line-between-groups: true
    
"css.validate": false,
"less.validate": false,
"scss.validate": false